# sudo docker compose up -d
services:
    php:
        build: .
        container_name: php
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./infrastructure/etc/.bashrc:/root/.bashrc
            - ./infrastructure/etc/ssl/certs:/etc/ssl/certs
            - ./infrastructure/etc/ssl/private:/etc/ssl/private
            - ./storage/app/public:/var/www/gflix/storage/app/public
            - .:/var/www/gflix
