# sudo docker-compose up -d
version: "3.9"
services:
    php:
        build: .
        container_name: php
        networks:
            - app
        depends_on:
            - db
        volumes:
            - ./etc/.bashrc:/root/.bashrc
            - .:/var/www/gflix
        ports:
            - "80:80"
    db:
        image: postgres:latest
        container_name: db
        restart: always
        environment:
            POSTGRES_DB: gflix
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - app
        ports:
            - "5432:5432"
volumes:
    db_data:
networks:
    app:
